# Generated by Django 4.1 on 2022-09-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='type',
            field=models.CharField(default='about', max_length=100),
        ),
    ]
