# Generated by Django 4.1 on 2022-09-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutme_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='state',
            field=models.IntegerField(default=1, max_length=10),
        ),
    ]
