# Generated by Django 4.1 on 2022-09-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_myusers_alter_aboutme_options_alter_info_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='about',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='myusers',
            name='image',
            field=models.ImageField(default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png', upload_to=''),
        ),
    ]
