# Generated by Django 4.1 on 2022-09-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_myusers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='facebook',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='myusers',
            name='instagram',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='myusers',
            name='twitter',
            field=models.CharField(default='', max_length=250),
        ),
    ]
