# Generated by Django 4.1 on 2022-09-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='created_by',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
